### ISSUE TITLE
good work

### ISSUE THREAD

**Issue by mxdi9i7** [Egrodo/cryptoClub#1]
i think it'll be super cool if you can sync real time market data to the website. there's lots of api's available online for that kind of data.

**Comment by Egrodo** [comment]
I'm not against the idea, but I'm struggling to come up with a natural place to put the information. We could establish a new page for the data, but then it would seem as if we're officially representing the coins (and which ones do we show?) Maybe we could put some unlabeled graph on the home page just for design purposes. Will play around with idea further.

**Comment by Egrodo** [comment]
Am looking into using coinmarketcap API to create a custom ticket at the top of the site, will see if that works.

**Comment by Egrodo** [comment]
Completed with live top 10 price ticker in about section.

**Comment by mxdi9i7** [comment]
good work
